alias d='docker'
alias dm='docker-machine'
alias drmf='docker rm -f $(docker ps -aq)'
alias k='kubectl'
alias kd='kubectl --namespace=deis'
alias kk='kubectl --namespace=kube-system'
alias l='ls'
alias ll='ls -al'
alias mk='minikube'
alias vu='vagrant up'
alias vs='vagrant ssh'
alias vd='vagrant destroy'
alias fucking='sudo'
